targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          create_to_json: true
          create_factory: true
          # Skip unknown fields to reduce code size
          ignore_unannotated: true
      
      # Temporarily skip go_router_builder to avoid issues
      go_router_builder|go_router:
        enabled: false
      
      riverpod_generator:
        enabled: true
        options:
          skip_cache: true
          # Performance optimizations for large codebases
          ignore_parameter_type_differences: true
      
      graphql_codegen:
        enabled: true
        options:
          addTypenameExcludedPaths:
            - subscription
          outputDirectory: __generated__
          clients:
            - graphql
            - graphql_flutter
          scalars:
            ISODateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
            Upload:
              type: MultipartFile
              fromJsonFunctionName: fileFromJson
              toJsonFunctionName: fileToJson
              import: package:tachidesk_sorayomi/src/utils/misc/scalars.dart
            LongString:
              type: String
              fromJsonFunctionName: longStringFromJson
              toJsonFunctionName: longStringToJson
              import: package:tachidesk_sorayomi/src/utils/misc/scalars.dart
            Cursor:
              type: int
              fromJsonFunctionName: cursorFromJson
              toJsonFunctionName: cursorToJson
              import: package:tachidesk_sorayomi/src/utils/misc/scalars.dart
          # Performance optimizations
          disable_context_marshalling: true
          fragments_glob: "lib/**/*.graphql"
          # Reduce memory usage
          disable_file_partial_schema: true