workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build (Unsigned)
    max_build_duration: 60
    environment:
      flutter: 3.27.0
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
      build_cache:
        paths:
          - $CM_BUILD_DIR/build
          - $CM_BUILD_DIR/.dart_tool
    triggers:
      push:
        branches:
          - main
          - master
      pull_request:
        branches:
          - main
          - master
    scripts:
      - name: Set up build environment
        script: |
          echo "Flutter version: $(flutter --version)"
          echo "Dart version: $(dart --version)"
      
      - name: Install dependencies
        script: |
          flutter pub get
      
      - name: Verify dependencies
        script: |
          flutter pub deps | grep -E "(flex_color_scheme|intl)"
      
      - name: Clean previous builds
        script: |
          flutter clean
          rm -rf .dart_tool/build
      
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Verify generated code
        script: |
          GENERATED_COUNT=$(find lib -name "*.g.dart" | wc -l)
          echo "Generated $GENERATED_COUNT .g.dart files"
          if [ $GENERATED_COUNT -lt 50 ]; then
            echo "Warning: Fewer generated files than expected"
          fi
      
      - name: Install iOS pods
        script: |
          cd ios && pod install
      
      - name: Build for iOS
        script: |
          flutter build ios --release --no-codesign
      
      - name: Create IPA
        script: |
          cd build/ios/iphoneos/
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r Sorayomi-unsigned.ipa Payload/
          mv Sorayomi-unsigned.ipa ../../
    artifacts:
      - build/Sorayomi-unsigned.ipa
    publishing:
      email:
        recipients:
          - wetw0rks.c0ding@protonmail.com
        notify:
          success: true
          failure: true
