workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # Note: Code signing is disabled for development builds
      # Set up automatic code signing in CodeMagic UI if needed
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Build iOS app (unsigned for development)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app/**
      - build/ios/Release-iphoneos/**/*.app
