workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build (Unsigned)
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "Sorayomi"
        BUNDLE_ID: "com.suwayomi.tachideskSorayomi"
        FLAVOR: "ios"
        # Increase build memory
        GRADLE_OPTS: -Xmx4096m -XX:MaxMetaspaceSize=1024m
    cache:
      cache_paths:
        - ~/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
        - $CM_BUILD_DIR/build
        - $CM_BUILD_DIR/.dart_tool
    # Automatic build triggers have been removed due to schema validation
    # Trigger builds manually or use alternative trigger methods
    scripts:
      - name: Pre-build setup
        script: |
          echo "=== Build Environment ==="
          echo "Flutter: $(flutter --version | head -n1)"
          echo "Dart: $(dart --version | head -n1)"
          echo "Xcode: $(xcodebuild -version | head -n1)"
          echo "Ruby: $(ruby --version)"
          echo "CocoaPods: $(pod --version)"
          echo "========================"
      
      - name: Install dependencies
        script: |
          set -e
          echo "=== Installing Flutter dependencies ==="
          flutter pub get

          echo "=== Verifying build_runner installation ==="
          # Check if build_runner is in dependencies instead of trying to run it
          flutter pub deps | grep -q "build_runner" || {
            echo "❌ build_runner not available"
            exit 1
          }
          echo "✅ build_runner is available"
      
      - name: Verify dependency resolution
        script: |
          flutter pub deps | grep -E "(flex_color_scheme|intl|flutter)"

      - name: Check GraphQL configuration
        script: |
          set -e
          echo "=== Checking GraphQL setup ==="

          if [ -f "graphql.config.yml" ]; then
            echo "✅ Found graphql.config.yml"
            cat graphql.config.yml
          else
            echo "❌ Missing graphql.config.yml"
          fi

          echo "=== Looking for GraphQL schema files ==="
          find lib -name "*.graphql" -o -name "schema.graphql" | head -20

          echo "=== Checking build.yaml ==="
          if [ -f "build.yaml" ]; then
            echo "✅ Found build.yaml"
            cat build.yaml
          else
            echo "⚠️  No build.yaml found"
          fi

      - name: Clean build environment
        script: |
          echo "=== Cleaning build environment ==="
          flutter clean
          rm -rf .dart_tool/build/
          rm -rf build/
          rm -rf .dart_tool/build_runner/
          echo "✅ Clean complete"

      - name: Generate code (GraphQL, Freezed, JSON)
        script: |
          set -e
          echo "=== Running code generation ==="
          
          # Show available memory before build
          echo "Memory before build_runner:"
          vm_stat | awk 'NR==1{printf("Total: "); next} /page size of/{printf $8"KB pages\n"} /[Pp]ages (free|active|inactive|speculative|wired)/{printf "%s: %d MB\n", $1, $2*4/1024}'

          # Pre-build validation
          echo "=== Validating GraphQL schema ==="
          if [ -f "lib/src/graphql/schema.graphql" ]; then
            echo "✅ Schema found: lib/src/graphql/schema.graphql"
            wc -l lib/src/graphql/schema.graphql
          else
            echo "❌ Schema not found!"
            exit 1
          fi

          echo "=== Validating dependencies ==="
          flutter pub deps | grep -E "(analyzer|build_resolvers|dart_style)" || true

          # Run build_runner with timeout to prevent infinite hangs
          timeout 3000 flutter pub run build_runner build --delete-conflicting-outputs --low-resources-mode || {
            echo "❌ build_runner failed or timed out"
            echo "Checking for build cache issues..."
            ls -la .dart_tool/build/ 2>/dev/null || echo "No build cache found"
            exit 1
          }

          echo "✅ Code generation completed"

      - name: Verify generated files
        script: |
          set -e

          echo "=== Generated file counts ==="
          GENERATED_COUNT=$(find lib -name "*.g.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ $GENERATED_COUNT .g.dart files"
          FREEZED_COUNT=$(find lib -name "*.freezed.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ $FREEZED_COUNT .freezed.dart files"
          GRAPHQL_COUNT=$(find lib -name "*.graphql.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ $GRAPHQL_COUNT .graphql.dart files"

          # Sample verification (don't fail if files don't exist - they might be generated elsewhere)
          echo "=== Sample generated files ==="
          find lib -name "*.g.dart" -type f 2>/dev/null | head -5 || echo "No .g.dart files found yet"
          find lib -name "*.freezed.dart" -type f 2>/dev/null | head -5 || echo "No .freezed.dart files found yet"
          find lib -name "*.graphql.dart" -type f 2>/dev/null | head -5 || echo "No .graphql.dart files found yet"

          # List all graphql generated files for debugging
          echo "=== GraphQL Generated Files ==="
          find lib -name "*.graphql.dart" 2>/dev/null || echo "No .graphql.dart files found"
      
      - name: Install iOS pods
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS app (unsigned)
        script: |
          set -e
          echo "=== Starting iOS build ==="

          # Build with verbose output
          flutter build ios --release --no-codesign \
            --build-name="0.6.4" \
            --build-number="${BUILD_NUMBER:-1}" \
            --verbose 2>&1 | tee flutter_build.log

          echo "✅ iOS build completed successfully"
      
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos/
          mkdir -p Payload
          cp -R Runner.app Payload/
          cd ..
          zip -r Sorayomi-unsigned.ipa iphoneos/Payload/
          mv Sorayomi-unsigned.ipa ./
      
      - name: Verify IPA
        script: |
          ls -lh build/ios/iphoneos/Sorayomi-unsigned.ipa
          echo "✅ IPA created successfully"
    artifacts:
      - build/ios/iphoneos/Sorayomi-unsigned.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_build.log
    publishing:
      email:
        recipients:
          - wetw0rks.c0ding@protonmail.com
        notify:
          success: true
          failure: true
