workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        provisioning_profile_type: development
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Build iOS app (unsigned for development)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/Runner.app
