workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build (Unsigned)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Build iOS app (unsigned, no codesign)
        script: |
          flutter build ios --release --no-codesign
      
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos/
          mkdir Payload
          cp -R Runner.app Payload/
          zip -r Sorayomi-unsigned.ipa Payload/
          mv Sorayomi-unsigned.ipa ../
    artifacts:
      - build/ios/Release-iphoneos/*.ipa
