workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build (Unsigned)
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "Sorayomi"
        BUNDLE_ID: "com.suwayomi.tachideskSorayomi"
        FLAVOR: "ios"
        # Increase build memory
        GRADLE_OPTS: -Xmx4096m -XX:MaxMetaspaceSize=1024m
    cache:
      cache_paths:
        - ~/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
        - $CM_BUILD_DIR/build
        - $CM_BUILD_DIR/.dart_tool
    # Automatic build triggers have been removed due to schema validation
    # Trigger builds manually or use alternative trigger methods
    scripts:
      - name: Pre-build setup
        script: |
          echo "=== Build Environment ==="
          echo "Flutter: $(flutter --version | head -n1)"
          echo "Dart: $(dart --version | head -n1)"
          echo "Xcode: $(xcodebuild -version | head -n1)"
          echo "Ruby: $(ruby --version)"
          echo "CocoaPods: $(pod --version)"
          echo "========================"
      
      - name: Install dependencies
        script: |
          set -e
          echo "=== Installing Flutter dependencies ==="
          echo "Current directory: $(pwd)"
          echo "Project files: $(ls -la | head -10)"
          
          flutter pub get
          
          # Wait a moment for file system to sync
          sleep 2
          
          echo "=== Verifying Generated.xcconfig exists ==="
          if [ -f "ios/Flutter/Generated.xcconfig" ]; then
            echo "✅ Generated.xcconfig created successfully"
            ls -la ios/Flutter/
            head -5 ios/Flutter/Generated.xcconfig
          else
            echo "❌ Generated.xcconfig not found!"
            echo "Flutter pub get may have failed or file was not created."
            echo "Contents of ios/Flutter/:"
            ls -la ios/Flutter/ || echo "ios/Flutter/ directory doesn't exist"
            exit 1
          fi

          echo "=== Verifying build_runner installation ==="
          # Check if build_runner is in dependencies instead of trying to run it
          flutter pub deps | grep -q "build_runner" || {
            echo "❌ build_runner not available"
            exit 1
          }
          echo "✅ build_runner is available"
      
      - name: Verify dependency resolution
        script: |
          flutter pub deps | grep -E "(flex_color_scheme|intl|flutter)"

      - name: Check GraphQL configuration
        script: |
          set -e
          echo "=== Checking GraphQL setup ==="

          if [ -f "graphql.config.yml" ]; then
            echo "✅ Found graphql.config.yml"
            cat graphql.config.yml
          else
            echo "❌ Missing graphql.config.yml"
          fi

          echo "=== Looking for GraphQL schema files ==="
          find lib -name "*.graphql" -o -name "schema.graphql" | head -20

          echo "=== Checking build.yaml ==="
          if [ -f "build.yaml" ]; then
            echo "✅ Found build.yaml"
            cat build.yaml
          else
            echo "⚠️  No build.yaml found"
          fi

      - name: Clean build environment
        script: |
          echo "=== Cleaning build environment ==="
          flutter clean
          rm -rf .dart_tool/build/
          rm -rf build/
          rm -rf .dart_tool/build_runner/
          echo "✅ Clean complete"

      - name: Generate code (GraphQL, Freezed, JSON)
        script: |
          set -e
          echo "=== Running code generation ==="
          
          # Show available memory before build
          echo "Memory before build_runner:"
          vm_stat | awk 'NR==1{printf("Total: "); next} /page size of/{printf $8"KB pages\n"} /[Pp]ages (free|active|inactive|speculative|wired)/{printf "%s: %d MB\n", $1, $2*4/1024}'

          # Pre-build validation
          echo "=== Validating GraphQL schema ==="
          if [ -f "lib/src/graphql/schema.graphql" ]; then
            echo "✅ Schema found: lib/src/graphql/schema.graphql"
            wc -l lib/src/graphql/schema.graphql
          else
            echo "❌ Schema not found!"
            exit 1
          fi

          echo "=== Validating code generation setup ==="
          echo "Riverpod providers to generate:"
          find lib -name "*.dart" -exec grep -l "@riverpod" {} \; 2>/dev/null | wc -l
          echo "Freezed classes to generate:"
          find lib -name "*.dart" -exec grep -l "@freezed" {} \; 2>/dev/null | wc -l
          echo "GraphQL queries to generate:"
          find lib -name "*.graphql" 2>/dev/null | wc -l

          echo "=== Running build_runner diagnostics ==="
          flutter pub run build_runner diagnose || echo "Diagnostics completed"

          # Run build_runner with extended timeout detection
          echo "=== Starting build_runner at $(date) ==="
          echo "This may take 30-60 minutes due to 134 riverpod providers and 31 GraphQL files..."
          
          # Use a background process to show progress
          (
            while true; do
              sleep 300  # Every 5 minutes
              echo "Build still running at $(date)..."
              if [ -d ".dart_tool/build" ]; then
                echo "Build cache size: $(du -sh .dart_tool/build 2>/dev/null | cut -f1)"
              fi
            done
          ) &
          
          BG_PID=$!
          
          flutter pub run build_runner build --delete-conflicting-outputs --low-resources-mode || {
            kill $BG_PID 2>/dev/null
            echo "❌ build_runner failed"
            echo "Last build outputs:"
            find .dart_tool/build -name "*.log" -type f 2>/dev/null | head -3 | xargs tail -20 2>/dev/null || echo "No logs found"
            exit 1
          }
          
          kill $BG_PID 2>/dev/null
          echo "=== build_runner completed at $(date) ==="

          echo "✅ Code generation completed"

      - name: Verify generated files
        script: |
          set -e

          echo "=== Generated file counts ==="
          GENERATED_COUNT=$(find lib -name "*.g.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ $GENERATED_COUNT .g.dart files"
          FREEZED_COUNT=$(find lib -name "*.freezed.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ $FREEZED_COUNT .freezed.dart files"
          GRAPHQL_COUNT=$(find lib -name "*.graphql.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ $GRAPHQL_COUNT .graphql.dart files"

          # Sample verification (don't fail if files don't exist - they might be generated elsewhere)
          echo "=== Sample generated files ==="
          find lib -name "*.g.dart" -type f 2>/dev/null | head -5 || echo "No .g.dart files found yet"
          find lib -name "*.freezed.dart" -type f 2>/dev/null | head -5 || echo "No .freezed.dart files found yet"
          find lib -name "*.graphql.dart" -type f 2>/dev/null | head -5 || echo "No .graphql.dart files found yet"

          # List all graphql generated files for debugging
          echo "=== GraphQL Generated Files ==="
          find lib -name "*.graphql.dart" 2>/dev/null || echo "No .graphql.dart files found"
      
      - name: Install iOS pods
        script: |
          set -e
          echo "=== Preparing for pod install ==="
          echo "Current directory: $(pwd)"
          echo "Checking for Generated.xcconfig before pod install:"
          if [ -f "ios/Flutter/Generated.xcconfig" ]; then
            echo "✅ Generated.xcconfig exists"
            echo "File contents:"
            head -3 ios/Flutter/Generated.xcconfig
          else
            echo "❌ Generated.xcconfig missing! Trying to regenerate..."
            flutter pub get
            if [ -f "ios/Flutter/Generated.xcconfig" ]; then
              echo "✅ Generated.xcconfig created after retry"
            else
              echo "❌ Still missing Generated.xcconfig"
              exit 1
            fi
          fi
          
          echo "=== Running pod install ==="
          cd ios
          pod install --repo-update
      
      - name: Build iOS app (unsigned)
        script: |
          set -e
          echo "=== Starting iOS build ==="
          echo "Current directory: $(pwd)"
          
          echo "=== Cleaning previous builds ==="
          flutter clean
          rm -rf build/ios/
          
          echo "=== Pre-build iOS project verification ==="
          if [ -f "ios/Runner.xcodeproj/project.pbxproj" ]; then
            echo "✅ Xcode project file exists"
          else
            echo "❌ Xcode project file missing!"
            exit 1
          fi
          
          if [ -f "ios/Runner/Info.plist" ]; then
            echo "✅ Info.plist exists"
          else
            echo "❌ Info.plist missing!"
            exit 1
          fi

          echo "=== Running flutter build ios (device only) ==="
          # Build with less verbosity but capture full output to log
          flutter build ios --release --no-codesign \
            --build-name="0.6.4" \
            --build-number="${BUILD_NUMBER:-1}" \
            > flutter_build.log 2>&1 || {
            echo "❌ iOS build failed"
            echo "=== Build output ==="
            tail -200 flutter_build.log
            exit 1
          }
          
          echo "=== iOS build completed successfully ==="
          
          echo "=== Verifying build output ==="
          if [ -d "build/ios/Release-iphoneos/Runner.app" ]; then
            echo "✅ Runner.app found in build/ios/Release-iphoneos/"
            ls -lh build/ios/Release-iphoneos/Runner.app
          else
            echo "❌ Runner.app not found!"
            echo "Contents of build/ios/:"
            find build/ios -type d -maxdepth 2 || true
            exit 1
          fi
      
      - name: Create unsigned IPA
        script: |
          set -e
          echo "=== Creating unsigned IPA ==="
          echo "Current directory before: $(pwd)"
          
          # Find where the build output actually is
          echo "=== Searching for build output ==="
          find build -name "Runner.app" -type d 2>/dev/null || echo "No Runner.app found in build/"
          
          if [ -d "build/ios/iphoneos" ]; then
            cd build/ios/iphoneos/
          elif [ -d "build/ios/Release-iphoneos" ]; then
            echo "⚠️  Using Release-iphoneos directory instead"
            cd build/ios/Release-iphoneos/
          else
            echo "❌ No iOS build output directory found!"
            echo "Contents of build/ios/:"
            ls -la build/ios/ || echo "build/ios/ doesn't exist"
            exit 1
          fi
          
          echo "Current directory after cd: $(pwd)"
          echo "Contents:"
          ls -la
          
          if [ ! -d "Runner.app" ]; then
            echo "❌ Runner.app not found!"
            exit 1
          fi
          
          echo "=== Creating Payload directory ==="
          mkdir -p Payload
          
          echo "=== Copying Runner.app to Payload/ ==="
          cp -R Runner.app Payload/
          
          echo "=== Creating IPA archive ==="
          cd ../..  # Go back to build/
          echo "Current directory: $(pwd)"
          echo "Contents:"
          ls -la
          
          if [ -d "ios/Release-iphoneos/Payload" ]; then
            echo "✅ Found Payload directory at ios/Release-iphoneos/Payload"
            zip -r Sorayomi-unsigned.ipa ios/Release-iphoneos/Payload/
            echo "✅ IPA created successfully"
            ls -lh Sorayomi-unsigned.ipa
          else
            echo "❌ Payload directory not found at expected location!"
            exit 1
          fi
          
          echo "=== Moving IPA to build/ios/ directory ==="
          mv Sorayomi-unsigned.ipa ios/
          echo "✅ IPA moved to ios/"
          
          echo "=== IPA creation completed ==="
          ls -lh ./*.ipa || echo "No IPA file created"
      
      - name: Verify IPA
        script: |
          set -e
          echo "=== Verifying IPA ==="
          echo "Current directory: $(pwd)"
          echo "Contents of build/ios/:"
          ls -la build/ios/ || echo "build/ios/ doesn't exist"
          
          if [ -f "build/ios/Sorayomi-unsigned.ipa" ]; then
            ls -lh build/ios/Sorayomi-unsigned.ipa
            echo "✅ IPA created successfully at build/ios/Sorayomi-unsigned.ipa"
          else
            echo "❌ IPA not found!"
            echo "Looking for IPA in build/ios/:"
            find build/ios/ -name "*.ipa" 2>/dev/null || echo "No IPA files found"
            exit 1
          fi
    artifacts:
      - build/ios/iphoneos/Sorayomi-unsigned.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_build.log
    publishing:
      email:
        recipients:
          - wetw0rks.c0ding@protonmail.com
        notify:
          success: true
          failure: true
