workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "Sorayomi"
        BUNDLE_ID: "com.suwayomi.tachideskSorayomi"
        FLAVOR: "ios"
        # Increase build memory
        GRADLE_OPTS: -Xmx4096m -XX:MaxMetaspaceSize=1024m
    cache:
      cache_paths:
        - ~/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
        - $CM_BUILD_DIR/build
        - $CM_BUILD_DIR/.dart_tool
    # Automatic build triggers have been removed due to schema validation
    # Trigger builds manually or use alternative trigger methods
    scripts:
      - name: Pre-build setup
        script: |
          echo "=== Build Environment ==="
          echo "Flutter: $(flutter --version | head -n1)"
          echo "Dart: $(dart --version | head -n1)"
          echo "Xcode: $(xcodebuild -version | head -n1)"
          echo "Ruby: $(ruby --version)"
          echo "CocoaPods: $(pod --version)"
          echo "========================"
      
      - name: Install dependencies
        script: |
          set -e
          echo "=== Installing Flutter dependencies ==="
          flutter pub get

          echo "=== Verifying build_runner installation ==="
          flutter pub run build_runner --version || {
            echo "❌ build_runner not available"
            exit 1
          }
      
      - name: Verify dependency resolution
        script: |
          flutter pub deps | grep -E "(flex_color_scheme|intl|flutter)"

      - name: Check GraphQL configuration
        script: |
          set -e
          echo "=== Checking GraphQL setup ==="

          if [ -f "graphql.config.yml" ]; then
            echo "✅ Found graphql.config.yml"
            cat graphql.config.yml
          else
            echo "❌ Missing graphql.config.yml"
          fi

          echo "=== Looking for GraphQL schema files ==="
          find lib -name "*.graphql" -o -name "schema.graphql" | head -20

          echo "=== Checking build.yaml ==="
          if [ -f "build.yaml" ]; then
            echo "✅ Found build.yaml"
            cat build.yaml
          else
            echo "⚠️  No build.yaml found"
          fi

      - name: Clean build environment
        script: |
          flutter clean
          rm -rf .dart_tool/build/
          rm -rf build/

      - name: Generate code (GraphQL, Freezed, JSON)
        script: |
          set -e
          echo "=== Running code generation ==="

          # Run build_runner with verbose output
          flutter pub run build_runner build --delete-conflicting-outputs --verbose || {
            echo "❌ build_runner failed, checking logs..."
            exit 1
          }

          echo "✅ Code generation completed"

      - name: Verify generated files
        script: |
          set -e

          GENERATED_COUNT=$(find lib -name "*.g.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ Generated $GENERATED_COUNT .g.dart files"
          FREEZED_COUNT=$(find lib -name "*.freezed.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ Generated $FREEZED_COUNT .freezed.dart files"
          GRAPHQL_COUNT=$(find lib -name "*.graphql.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ Generated $GRAPHQL_COUNT .graphql.dart files"

          # Check for critical generated files
          CRITICAL_FILES=(
            "lib/src/features/quick_open/domain/quick_search_result.g.dart"
            "lib/src/features/quick_open/domain/quick_search_result.freezed.dart"
          )

          for file in "${CRITICAL_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing critical file: $file"
              exit 1
            else
              echo "✅ Found: $file"
            fi
          done

          if [ "$GENERATED_COUNT" -lt 50 ]; then
            echo "⚠️  Warning: Expected at least 50 .g.dart files, found $GENERATED_COUNT"
          fi

          # List all graphql generated files for debugging
          echo "=== GraphQL Generated Files ==="
          find lib -name "*.graphql.dart" 2>/dev/null || echo "No .graphql.dart files found"
      
      - name: Install iOS pods
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS app (unsigned)
        script: |
          set -e
          echo "=== Starting iOS build ==="

          # Build with verbose output
          flutter build ios --release --no-codesign \
            --build-name="0.6.4" \
            --build-number="${BUILD_NUMBER:-1}" \
            --verbose 2>&1 | tee flutter_build.log

          echo "✅ iOS build completed successfully"
      
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos/
          mkdir -p Payload
          cp -R Runner.app Payload/
          cd ..
          zip -r Sorayomi-unsigned.ipa iphoneos/Payload/
          mv Sorayomi-unsigned.ipa ./
      
      - name: Verify IPA
        script: |
          ls -lh build/ios/iphoneos/Sorayomi-unsigned.ipa
          echo "✅ IPA created successfully"
    artifacts:
      - build/ios/iphoneos/Sorayomi-unsigned.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_build.log
    publishing:
      email:
        recipients:
          - wetw0rks.c0ding@protonmail.com
        notify:
          success: true
          failure: true
