workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build (Unsigned)
    max_build_duration: 60
    environment:
      flutter: 3.27.0  # Compatible with intl 0.19.0
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Show dependency tree
        script: |
          flutter pub deps | grep intl
      
      - name: Update dependencies
        script: |
          flutter clean
          flutter pub upgrade
      
      - name: Prepare build
        script: |
          rm -rf .dart_tool/build
          flutter pub run build_runner clean
      
      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs --verbose
      
      - name: Verify generated files
        script: |
          if [ ! -f "lib/src/routes/router_config.g.dart" ]; then
            echo "ERROR: Critical file missing"
            exit 1
          fi
          echo "Generated files: $(find lib -name '*.g.dart' | wc -l) files"
      
      - name: Install iOS dependencies
        script: |
          cd ios && pod install
      
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
      
      - name: Package IPA
        script: |
          cd build/ios/iphoneos/
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r Sorayomi-unsigned.ipa Payload/
          mv Sorayomi-unsigned.ipa ../
    artifacts:
      - build/ios/Release-iphoneos/*.ipa
