workflows:
  sorayomi-ios:
    name: Sorayomi iOS Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.27.0
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "Sorayomi"
        BUNDLE_ID: "com.suwayomi.tachideskSorayomi"
        FLAVOR: "ios"
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
      build_cache:
        paths:
          - $CM_BUILD_DIR/build
          - $CM_BUILD_DIR/.dart_tool
    triggers:
      push:
        branches:
          - main
          - master
      pull_request:
        branches:
          - main
          - master
    scripts:
      - name: Pre-build setup
        script: |
          echo "=== Build Environment ==="
          echo "Flutter: $(flutter --version | head -n1)"
          echo "Dart: $(dart --version | head -n1)"
          echo "Xcode: $(xcodebuild -version | head -n1)"
          echo "Ruby: $(ruby --version)"
          echo "CocoaPods: $(pod --version)"
          echo "========================"
      
      - name: Install dependencies
        script: |
          flutter pub get
      
      - name: Verify dependency resolution
        script: |
          flutter pub deps | grep -E "(flex_color_scheme|intl|flutter)"
      
      - name: Clean build environment
        script: |
          flutter clean
          rm -rf .dart_tool/build/
      
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Verify generated files
        script: |
          GENERATED_COUNT=$(find lib -name "*.g.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ Generated $GENERATED_COUNT .g.dart files"
          FREEZED_COUNT=$(find lib -name "*.freezed.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ Generated $FREEZED_COUNT .freezed.dart files"
          GRAPHQL_COUNT=$(find lib -name "*.graphql.dart" 2>/dev/null | wc -l | tr -d ' ')
          echo "✓ Generated $GRAPHQL_COUNT .graphql.dart files"
          
          if [ "$GENERATED_COUNT" -lt 50 ]; then
            echo "⚠️  Warning: Expected at least 50 .g.dart files, found $GENERATED_COUNT"
          fi
      
      - name: Install iOS pods
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS app (unsigned)
        script: |
          flutter build ios --release --no-codesign --build-name="0.6.4" --build-number="$BUILD_NUMBER"
      
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos/
          mkdir -p Payload
          cp -R Runner.app Payload/
          cd ..
          zip -r Sorayomi-unsigned.ipa iphoneos/Payload/
          mv Sorayomi-unsigned.ipa ./
      
      - name: Verify IPA
        script: |
          ls -lh build/ios/Release-iphoneos/Sorayomi-unsigned.ipa
          echo "✅ IPA created successfully"
    artifacts:
      - build/ios/Release-iphoneos/Sorayomi-unsigned.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_build.log
    publishing:
      email:
        recipients:
          - wetw0rks.c0ding@protonmail.com
        notify:
          success: true
          failure: true
      # Uncomment below for TestFlight/App Store publishing (requires code signing)
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
      #   submit_to_app_store: false
